name: Build Kivy APK
on:
  push:
    branches: [ main ]
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 配置Python3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 安装系统依赖
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev

      - name: 安装打包工具
        run: |
          pip install --break-system-packages buildozer==1.4.0 cython==3.0.0 meson ninja "kivy[base]"

      - name: 编译安卓APK
        run: buildozer android debug

      - name: 上传打包好的APK文件
        uses: actions/upload-artifact@v4
        with:
          path: bin/*.apk
          name: 生成的安卓安装包
